# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "RDLoveSeekerExample" do

pod 'RDLoveSeeker', :git => 'git@github.com:restorando/RDLoveSeeker.git'
#pod 'RDLoveSeeker', :path => '../../RDLoveSeeker.podspec'

end

target "RDLoveSeekerExampleTests" do

pod 'OCMock'

end

